version: 3

dotenv: ['{{.ENV}}.env']

tasks:
  build:
    vars:
      GOOS:
        sh: go env GOOS
      GOARCH:
        sh: go env GOARCH
    cmds:
      - go build -o release/{{.GOOS}}/{{.GOARCH}}/prio

  migrate:
    cmds:
      - migrate -path migrations/mysql -database "mysql://{{.PRIO_DB_USER}}:{{.PRIO_DB_PASSWORD}}@tcp(127.0.0.1:3306)/prio" up

  start:
    deps: [build, migrate]
    vars:
      GOOS:
        sh: go env GOOS
      GOARCH:
        sh: go env GOARCH
    cmds:
      - ./release/{{.GOOS}}/{{.GOARCH}}/prio worker
