version: 3

dotenv: ['{{.ENV}}.env']

tasks:
  build:
    vars:
      GOOS:
        sh: go env GOOS
      GOARCH:
        sh: go env GOARCH
    cmds:
      - go build -o release/{{.GOOS}}/{{.GOARCH}}/worker

  start:
    deps: [build]
    vars:
      GOOS:
        sh: go env GOOS
      GOARCH:
        sh: go env GOARCH
    cmds:
      - ./release/{{.GOOS}}/{{.GOARCH}}/worker start
